### ISSUE TITLE
LDA Assertion 

### ISSUE THREAD

**Issue by lopeLH** [wihoho/FaceRecognition#2]
Hi, I am trying to use this library for my end-of-degree project at the university of Salamanca (Spain). I need to perform LDA over a set of image where I have only one picture per individual, so the second assertion on the LDA constructor fails:

![image](https://cloud.githubusercontent.com/assets/7440734/6996746/3f26d832-db9b-11e4-8952-59d2bbf9374c.png)

My question is, Is this assertion truly needed for the algorithm or just a sort of advice to get good results? I mean, if I remove this assertion will the algorithm work properly?

Thanks in advance.
Daniel López

**Comment by wihoho** [comment]
Hi, I can not remember why the assertion is there. I think your guess is correct. It shall just be a sort of advice to get good results. If the samples are less than the size of class, I do not think there is any meaning to classify. 

So I think the algorithm shall work fine in your case. but the result may not be good enough.

**Comment by lopeLH** [comment]
I'll let you now if it works.
Thanks a lot, and congratulations on your work.
