### ISSUE TITLE
[q] Can this project be used for face detection only?

### ISSUE THREAD

**Issue by salamanders** [wihoho/FaceRecognition#4]
I was struggling with using OpenCV's face detection lib through Java - it seemed to miss a lot of faces in a video.  Can this project be used to do face detection and get a reasonable bounding box, or feature location?  I saw the main class was doing face recognition, but I wasn't sure how stand-alone the detection aspects could be.  Thanks!

**Comment by zzlover** [comment]
up

**Comment by wihoho** [comment]
No
